# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Peter Grillot - Web Developer
email: petergrillot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Full Stack Dev with a focus on modern Javascript frameworks. I love coding, learning and playing music. I am from Washington, D.C
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://petergrillot.github.io" # the base hostname & protocol for your site
github_username:  petergrillot

# Build settings
markdown: kramdown
